"""Self-loop pipeline wrapper: PR targets self-loop branch."""

from __future__ import annotations

import subprocess
from pathlib import Path

from schema.config import AgentConfig
from schema.issue import Issue
from tools.log import get_logger
from tools.setup import run_setup, _run_hash
from pipeline import _run_pipeline_steps, _run_report, _post_pr_comment

log = get_logger(__name__)


def run_self_loop_pipeline(
    issue_url: str,
    repo_local_path: str,
    config: dict,
) -> tuple[str, str, str | None]:
    """Run the fix pipeline and create a PR targeting the self-loop branch.

    Returns (outcome, reason, pr_url).
    """
    log.debug(f"run_self_loop_pipeline: issue_url={issue_url!r}")

    guidelines = ""
    guidelines_path = config.get("guidelines_path")
    if guidelines_path:
        try:
            guidelines = Path(guidelines_path).read_text(encoding="utf-8")
        except Exception as e:
            log.warning(f"Could not read guidelines: {e}")

    issue = run_setup(issue_url, local_path=repo_local_path)

    agent_config = AgentConfig(
        model_name=config.get("fix_model"),
        max_steps=config.get("per_run_max_steps"),
        budget=config.get("per_run_budget_usd"),
        model_api_key=None,
        model_endpoint=None,
    )

    outcome = "fail"
    reason = "unknown"
    pr_url: str | None = None

    try:
        outcome, reason = _run_pipeline_steps(issue, guidelines, agent_config)
        if outcome == "pass":
            pr_url = _push_self_loop_pr(issue, config.get("self_loop_branch", "self-loop"))
            log.debug(f"PR created: {pr_url}")
    except Exception as e:
        log.error(f"Self-loop pipeline failed: {e}", exc_info=True)
        outcome = "fail"
        reason = "exception"
    finally:
        _run_report(issue, outcome, agent_config)

    return outcome, reason, pr_url


def _push_self_loop_pr(issue: Issue, base_branch: str) -> str:
    """Push branch and create PR targeting base_branch instead of main."""
    repo_dir = issue["dir"]

    push = subprocess.run(
        ["git", "push", "origin", "HEAD"],
        cwd=repo_dir, capture_output=True, text=True,
    )
    if push.returncode != 0:
        raise RuntimeError(f"git push failed: {push.stderr}")

    commit_title = subprocess.run(
        ["git", "log", "-1", "--format=%s"],
        cwd=repo_dir, capture_output=True, text=True,
    ).stdout.strip()

    pr = subprocess.run(
        ["gh", "pr", "create",
         "--title", f"[self-loop] {commit_title}",
         "--body", f"Closes {issue['url']}\n\nGenerated by self-loop agent.",
         "--base", base_branch],
        cwd=repo_dir, capture_output=True, text=True,
    )
    if pr.returncode != 0:
        raise RuntimeError(f"gh pr create failed: {pr.stderr}")

    return pr.stdout.strip()
