"""Summary agent: squash commits, create/update PR, poll CI."""

from __future__ import annotations

from pathlib import Path

from agents.base import AgentResult, run_agent
from schemas.state import CIStatus, FailureSource, Step
from tools.fs import grep, list_dir, read_file
from tools.manifests import SUMMARY_MANIFEST, build_tools
from tools.shell import execute_cli
from tools.state import read_state, write_state

_SYSTEM_PROMPT = """\
You are the Summary agent in an automated GitHub issue → pull request pipeline.

Your job:
1. Read ISSUE.md, PLAN.md, CHANGES.md, VALIDATE.md, and TEST.md.
2. Squash all commits on the feature branch into one (non-interactive rebase).
3. Create or update the pull request:
   - If no PR exists: `gh pr create --title "..." --body "..."`
   - If PR already exists (loop-back): force-push only, do NOT create a new PR.
4. Poll CI status: `gh pr checks <pr_url>`
5. Write SUMMARY.md with PR URL, CI status, total loop count, and total cost.

## Squash rebase

Run non-interactively:
  git rebase --autosquash origin/main

Or use:
  git reset --soft $(git merge-base HEAD origin/main)
  git commit -m "agent: <issue title> (#<issue number>)"

## PR template

Title: `agent: <issue title> (#<issue number>)`

Body:
```
## Summary
<bullet points from CHANGES.md>

## Test results
<brief summary from TEST.md>

Closes #<issue number>

🤖 Generated by gh-issue-to-pr pipeline
```

## CI polling

After push, run `gh pr checks <pr_url>` and wait for CI to finish.
If CI fails: write failure info to SUMMARY.md, set result accordingly.

## SUMMARY.md format (success)

```
# Pipeline Summary

- PR URL: <url>
- CI status: pass / fail
- Loop count: <n>
- Total cost: $<cost>
```

## Rules

- Always use `--force-with-lease` for push, never `--force`.
- Do NOT create a new PR if `pr_url` is already set.
- If CI fails, output classification: `ci`.
"""


_SUMMARY_ALLOWLIST = [
    ("git", "rebase"),
    ("git", "reset"),
    ("git", "commit"),
    ("git", "push"),
    ("git", "log"),
    ("git", "merge-base"),
    ("git", "rev-parse"),
    ("git", "status"),
    ("gh", "pr"),
]


def run_summary_agent(run_dir: Path) -> AgentResult:
    run_dir = Path(run_dir)
    state = read_state(run_dir)
    repo_root = _repo_root(run_dir)

    # Build user prompt with all prior context
    context_parts = []
    for fname in ("ISSUE.md", "PLAN.md", "CHANGES.md", "VALIDATE.md", "TEST.md"):
        path = run_dir / fname
        if path.exists():
            context_parts.append(f"### {fname}\n\n{_read_file_safe(path)}")

    pr_url_info = f"Existing PR URL: {state.pr_url}" if state.pr_url else "No PR created yet."
    cost_info = f"Cost so far: ${state.cost_spent_usd:.4f}"
    loop_info = f"Global loop count: {state.loop_count}"

    user_prompt = "\n".join([
        "## Prior agent outputs\n",
        "\n\n".join(context_parts),
        f"\n## State\n{pr_url_info}\n{cost_info}\n{loop_info}",
        f"\nBranch: {state.branch_name}",
        f"Repository root: {repo_root}",
        f"Run directory (write SUMMARY.md here): {run_dir}",
        "\n## Instructions\nSquash commits, push, create/update PR, poll CI, write SUMMARY.md.",
    ])

    def _write_summary_md(path: str, content: str):
        if Path(path).name == "SUMMARY.md":
            p = run_dir / "SUMMARY.md"
            p.write_text(content, encoding="utf-8")
            return {"ok": True, "output": f"Written: {p}", "error": None}
        return {"ok": False, "output": "", "error": "Summary agent may only write SUMMARY.md."}

    def _execute_cli_fn(cmd: str):
        return execute_cli(cmd, _SUMMARY_ALLOWLIST, cwd=repo_root)

    handlers = {
        "list_dir": lambda path: list_dir(path, repo_root=repo_root),
        "read_file": lambda path: read_file(path, repo_root=repo_root),
        "grep": lambda pattern, path, flags="": grep(pattern, path, repo_root=repo_root, flags=flags),
        "execute_cli": _execute_cli_fn,
        "write_file": _write_summary_md,
    }

    from tools.manifests import ToolManifest
    summary_manifest_with_write = ToolManifest(
        agent_name="summary",
        tool_names=["list_dir", "read_file", "grep", "execute_cli", "write_file"],
    )
    from tools.manifests import build_tools as _build_tools

    result = run_agent(
        agent_name="summary",
        system_prompt=_SYSTEM_PROMPT,
        user_prompt=user_prompt,
        tool_schemas=_build_tools(summary_manifest_with_write),
        tool_handlers=handlers,
        run_dir=run_dir,
    )

    # Parse SUMMARY.md for PR URL, CI status
    summary_md_path = run_dir / "SUMMARY.md"
    if summary_md_path.exists():
        summary_content = summary_md_path.read_text(encoding="utf-8")
        pr_url = _extract_pr_url(summary_content)
        ci_status = _extract_ci_status(summary_content)

        state = read_state(run_dir)
        if pr_url and not state.pr_url:
            state.pr_url = pr_url
        if ci_status:
            state.ci_status = CIStatus.pass_ if ci_status == "pass" else CIStatus.fail

        if ci_status == "fail":
            state.failure_source = FailureSource.ci
            state.last_failure_reason = "CI failed after push"
            state.loop_count += 1
            state.local_loop_count = 0
            state.current_step = Step.plan
            write_state(run_dir, state)
            return AgentResult(
                ok=False,
                output=result.output,
                tokens_in=result.tokens_in,
                tokens_out=result.tokens_out,
                cost_usd=result.cost_usd,
                failure_source="ci",
                failure_reason="CI failed after push",
            )

        state.current_step = Step.report
        write_state(run_dir, state)

    return result


def _extract_pr_url(content: str) -> str | None:
    import re
    m = re.search(r"https://github\.com/[^\s]+/pull/\d+", content)
    return m.group(0) if m else None


def _extract_ci_status(content: str) -> str | None:
    import re
    m = re.search(r"CI status:\s*(pass|fail)", content, re.IGNORECASE)
    return m.group(1).lower() if m else None


def _read_file_safe(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else f"({path.name} not found)"


def _repo_root(run_dir: Path) -> Path:
    return run_dir.parent.parent
